
export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 md:py-20">
      <header className="mb-12">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-center">Terms and Conditions</h1>
        <p className="text-center text-muted-foreground mt-2">Last updated: May 2025</p>
      </header>

      <div className="prose prose-lg dark:prose-invert mx-auto max-w-3xl bg-card p-8 rounded-lg shadow-xl">
        <p>
          By using our application (the “Service”), you agree to the following Terms and Conditions:
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Account Use and Restrictions</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Each user is allowed one account only. Creating multiple free accounts to bypass usage limits is strictly prohibited.
          </li>
          <li>
            Account credentials must not be shared. Your license is tied to you or your organization and is non-transferable.
          </li>
          <li>
            Any abuse of account limits, sharing, or automated account creation may result in immediate suspension or termination of access.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Purpose of Use</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            This Service is intended for use by authorized contractors, vendors, and agencies performing transcription and translation work specifically related to Bureau of Prisons (BOP) recorded communications.
          </li>
          <li>
            Transcriptions generated by the Service are to be used only for official and lawful purposes, in alignment with your contract or agreement with BOP or its partner agencies.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Confidentiality and Non-Disclosure</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            All data processed through the Service is treated as confidential. We operate under strict Non-Disclosure Agreement (NDA) principles, and all project data is not stored beyond your plan’s retention period.
          </li>
          <li>
            You agree to keep all transcriptions secure and not to distribute or repurpose any content outside of BOP-related obligations.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Legal Liability</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            While we take data security and platform integrity seriously, we are not responsible for any legal consequences arising from your misuse of transcriptions or data processed via the Service.
          </li>
          <li>
            You agree to hold us harmless against any claims, liabilities, damages, or costs (including legal fees) resulting from your use or misrepresentation of the Service’s output.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Modifications and Termination</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            We reserve the right to modify these Terms at any time. Continued use of the Service constitutes acceptance of the revised terms.
          </li>
          <li>
            We may suspend or terminate access at our discretion for violations of these Terms.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Contact</h2>
        <p>
          If you have questions or need support, contact us at:
          <br />
          Email: <a href="mailto:contact@howw2.com" className="text-primary hover:underline">contact@howw2.com</a>
        </p>
      </div>
    </div>
  );
}
